//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::domains::Entity as Domains;
pub use super::example_table::Entity as ExampleTable;
pub use super::shortlinks::Entity as Shortlinks;
pub use super::users::Entity as Users;
